### ISSUE TITLE
commands not working on ubuntu

### ISSUE THREAD

**Issue by NTCoding** [ostinelli/SublimErl#57]
SublimErl looks fantastic and I was really excited to install it. Happily, the install went perfectly. Unfortunately, none of the commands appear to work. Here's an example from ST's console when I try to run ctrl + alt + p to navigate to a function definition:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./sublimerl_core.py", line 308, in run
  File "./sublimerl_function_search.py", line 103, in run_command
  File "./sublimerl_function_search.py", line 48, in show
  File "./sublimerl_function_search.py", line 58, in set_search_completions
  File ".\posixpath.py", line 67, in join
AttributeError: 'NoneType' object has no attribute 'endswith'

I'm running on ubuntu 12.04

Thanks

**Comment by ostinelli** [comment]
Have you installed the [Erlang man pages](http://www.erlang.org/download.html) as suggested in the README?

**Comment by NTCoding** [comment]
man pages were installed but I didn't have a copy of rebar in my bin folder. now everything is working :)

I've add a new life-lesson (www.mylifelessons.net) to always read the readme

**Comment by ostinelli** [comment]
No worries :) I still need to get the time to implement issue #45 and #55 which will ease this kind of pain :)
