### ISSUE TITLE
Installation on Mac 10.9

### ISSUE THREAD

**Issue by sononix** [ostinelli/SublimErl#75]
just wondering is there anyone else having trouble with the installation of this package 

tried running on ST 2 and 3 and still cant get it to work - I see a single error in the console 
is there any way to check 

<code>
Traceback (most recent call last):
  File "./sublime_plugin.py", line 175, in on_load
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 174, in <lambda>
  File "./sublimerl_completion.py", line 232, in on_load
  File "./sublimerl_core.py", line 224, in **init**
  File "./sublimerl_core.py", line 259, in set_app_name
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/posixpath.py", line 67, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
</code> 

Any suggestions of being able to compile a simple hello.erl file 
<code>
-module (hello).
-export ([start/0]).

start() ->
io:format("Hello World").
</code>

getting error of 
<code>
[Errno 2] No such file or directory: 'erl'
[cmd: ['erl', '-compile', '/Users/studio/CODE/Erlang/hello.erl']]
[dir: /Users/studio/CODE/Erlang]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
</code>

this is using the base build file in ST2- would it be better to create my own build file

**Comment by ostinelli** [comment]
As the error states, it seems that `erl` is not in your path. Is it?

**Comment by sononix** [comment]
in the mac path - I guess it is as I can easily compile erlang from the command line ... 

installed Sublime-Erlang now
https://github.com/fjl/Sublime-Erlang

instead of the default Erlang package and getting strange feedback in the prompt saying the compile is fine ever this there are syntax errors in the code - very strange indeed its almost like the build settings are being ignored - could it be a rebar issue not sure how to test this though...

trying to strip everything back in Sublime to track to see if any other package are causing the conflict 

tks
M
